### ISSUE TITLE
Improve autoconfigure module

### ISSUE THREAD

**Issue by eddumelendez** [openzipkin-contrib/zipkin-storage-forwarder#1]
The current `spring-boot` support can be improved. This is regarding the structure of `autoconfigure` module.

* Make `http` and `kafka` packages in `autoconfigure` instead of modules
* Provide auto-configuration providing starters which will provide the right dependencies and will enable `http` or `kafka`

Also, this new approach can take advantage of adding `additional-spring-configuration-metadata.json` file for `zipkin.storage.type` which will provide IDE support for developers to choose between `http-forwarder` or `kafka-forwarder`.

**Comment by eddumelendez** [comment]
I can work on it :)

**Comment by jeqo** [comment]
Sounds great!
Fixed by #2 

Thanks Eddu!

**Comment by eddumelendez** [comment]
Can we reopen it? This is not solved by #2

**Comment by jeqo** [comment]
Sorry I rushed to merge it, feel free to open a new PR to complete the changes

**Comment by codefromthecrypt** [comment]
zipkin internally uses a different loading mechanism which is faster and less problematic than spring boot as they often change loading things between releases. it is currently in #11

**Comment by codefromthecrypt** [comment]
I think there is nothing to do here, because the module system is being used as intended and matches exactly zipkin-aws zipkin-gcp and zipkin-storage-kafka
