### ISSUE TITLE
Add starters for kafka and http forwarder

### ISSUE THREAD

**Issue by eddumelendez** [openzipkin-contrib/zipkin-storage-forwarder#5]
Once #4 is merged. New modules can be created in order to provide starters for both kafka and http forwarder

**Comment by codefromthecrypt** [comment]
do we need starters? unless making custom servers it probably is fine to just publish our modules and docker image ya?

**Comment by codefromthecrypt** [comment]
zipkin is not normal spring and explicitly states it doesn't support traditional extension via spring, so adding starters here would cause more confusion on this topic.

https://github.com/openzipkin/zipkin/blob/e3dec438a573e8eba709cf9bf9abfd1abfc8a669/zipkin-server/README.md#zipkin-server

If, for example, we tried to support custom servers, we couldn't easily upgrade to spring boot 3 or even out of spring if we needed to. Spring has always been an internal detail of the server.
