### ISSUE TITLE
Clash in properties

### ISSUE THREAD

**Issue by eddumelendez** [openzipkin-contrib/zipkin-storage-forwarder#6]
The same property key is used in this project and also in `zipkin-storage-kafka`

https://github.com/openzipkin-contrib/zipkin-storage-kafka/blob/d24267b6647f016084914513ffbb304a1cb39254/autoconfigure/src/main/java/zipkin2/autoconfigure/storage/kafka/ZipkinKafkaStorageAutoConfiguration.java#L25

I suggest to rename the existing one in this project to `zipkin.storage-forwarder.type` with values `http` and `kafka`

**Comment by codefromthecrypt** [comment]
all good I think as the type currently is "http-forwarder" or "kafka-forwarder"?

**Comment by codefromthecrypt** [comment]
this was switched to `  @ConditionalOnProperty(name = "zipkin.storage.type", havingValue = "kafka-forwarder")` some time back

**Comment by codefromthecrypt** [comment]
that and `@ConditionalOnProperty(name = "zipkin.storage.type", havingValue = "http-forwarder")`
